services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./Brocker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./Brocker/data:/mosquitto/data
      - ./Brocker/log:/mosquitto/log
    networks:
      - network-1
    restart: unless-stopped
  gateway:
    build:
      context: ./GateWay
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
    tty: true
    networks:
      - network-1
    depends_on:
      - mosquitto
  temperature_sensor:
    build:
      context: ./sensors/sensor-temperature
      dockerfile: Dockerfile
    depends_on:
      - gateway
    networks:
      - network-1
  pressure_sensor:
    build:
      context: ./sensors/sensor-pressure
      dockerfile: Dockerfile
    depends_on:
      - gateway
    networks:
      - network-1
  heartrate_sensor:
    build:
      context: ./sensors/sensor-heartrate
      dockerfile: Dockerfile
    depends_on:
      - gateway
    networks:
      - network-1
networks:
  network-1:
    driver: bridge